export const allBikesList = [
  {
    type: "Standard",
    bikes: [
      {
        id: 1,
        name: "CB1000R",
        MSRP: 11999,
        image: "/images/c4.png",
        Engine: "988cc liquid-cooled DOHC inline-four",
        Horsepower: "54 hp",
        Torque: "73 lb-ft",
        Weight: "345 lbs",
      },
      {
        id: 2,
        name: "CB650R",
        MSRP: 6999,
        image: "/images/c.png",
        Engine: "471cc parallel-twin DOHC",
        Horsepower: "54 hp",
        Torque: "73 lb-ft",
        Weight: "345 lbs",
      },
      {
        id: 3,
        name: "SCL500",
        MSRP: 5999,
        image: "/images/prc.png",
        Engine: "988cc liquid-cooled DOHC inline-four",
        Horsepower: "54 hp",
        Torque: "73 lb-ft",
        Weight: "345 lbs",
      },
      {
        id: 4,
        name: "CB300R",
        MSRP: 5149,
        image: "/images/cb3.png",
        Engine: "988cc liquid-cooled DOHC inline-four",
        Horsepower: "54 hp",
        Torque: "73 lb-ft",
        Weight: "345 lbs",
      },
    ],
  },
  {
    type: "Cruiser",
    bikes: [
      {
        id: 1,
        name: "Fury",
        MSRP: 11499,
        image: "/images/fury.png",
        Engine: "1312cc liquid-cooled 52-degree V-twin four-stroke",
        Horsepower: "53.7 hp",
        Torque: "79 lb-ft",
        Weight: "666 lbs",
      },
      {
        id: 2,
        name: "Shadow Phantom ABS",
        MSRP: 8699,
        image: "/images/shadow.png",
        Engine: "745cc liquid-cooled 52-degree V-twin four-stroke",
        Horsepower: "44.6 hp",
        Torque: "47.9 lb-ft",
        Weight: "553 lbs",
      },
      {
        id: 3,
        name: "Shadow Aero",
        MSRP: 7949,
        image: "/images/aero.png",
        Engine: "745cc liquid-cooled 52-degree V-twin four-stroke",
        Horsepower: "67 hp",
        Torque: "60 lb-ft",
        Weight: "44 ft.-lbS",
      },
      {
        id: 4,
        name: "Rebel 1100T",
        MSRP: 10799,
        image: "/images/Rebel.png",
        Engine: "1083cc liquid-cooled Unicam® parallel-twin engine",
        Horsepower: "86 hp",
        Torque: "72 lb-feet",
        Weight: "487 lbs",
      },
    ],
  },
  {
    type: "Roadster",
    bikes: [
      {
        id: 1,
        name: "G 310 R",
        MSRP: 5999,
        image: "/images/g3png.png",
        Engine: "DOHC, liquid-cooled inline-four; 4 valves/cyl.",
        Horsepower: "143 HP",
        Torque: "64.45 lb-feet",
        Weight: "407 lbs",
      },
      {
        id: 2,
        name: "Yamaha XSR 900",
        MSRP: 10599,
        image: "/images/yamah.webp",
        Engine:
          "890cc liquid-cooled DOHC inline 3-cylinder 4-stroke; 12 valves",
        Horsepower: "106.0 hp",
        Torque: "69 lb-feet",
        Weight: "425 lbs",
      },
      {
        id: 3,
        name: "BMW r1250",
        MSRP: 16120,
        image: "/images/bmw-1250.webp",
        Engine: "Two-cylinder, Boxer",
        Horsepower: "136 hp",
        Torque: "106 lb-feet",
        Weight: "527 lbs",
      },
      {
        id: 4,
        name: "Ducati Monster 1200",
        MSRP: 16120,
        image: "/images/Ducati-monster.png",
        Engine: "Testastretta 11",
        Horsepower: "147 hp",
        Torque: "91 lb-feet",
        Weight: "470 lbs",
      },
    ],
  },
  {
    type: "Off Road",
    bikes: [
      {
        id: 1,
        name: "CRF450X",
        MSRP: 16000,
        image: "/images/crf.webp",
        Engine: "450cc liquid-cooled Unicam single-cylinder",
        Horsepower: "41.1 hp",
        Torque: "41.30 lb-feet",
        Weight: "275 lbs",
      },
      {
        id: 2,
        name: "CRF125F - Big Wheel",
        MSRP: 8699,
        image: "/images/crfbig-1.png",
        Engine: "125cc air-cooled single-cylinder",
        Horsepower: "41.1 hp",
        Torque: "41 lb-feet",
        Weight: "200 lbs",
      },
      {
        id: 3,
        name: "CRF110F",
        MSRP: 2699,
        image: "/images/crf11.png",
        Engine: "109cc air-cooled single-cylinder",
        Horsepower: "41 hp",
        Torque: "8.85 lb-feet",
        Weight: "300 lbs",
      },
      {
        id: 4,
        name: "CRF50F",
        MSRP: 1999,
        image: "/images/crf5.png",
        Engine: "50cc air-cooled single-cylinder",
        Horsepower: "39 hp",
        Torque: "8.89 lb-feet",
        Weight: "100 lbs",
      },
    ],
  },
  {
    type: "Super",
    bikes: [
      {
        id: 1,
        name: "Hayabusa",
        MSRP: 20000,
        image: "/images/haya.png",
        Engine: "50cc air-cooled single-cylinder",
        Horsepower: "300 hp",
        Torque: "245 lb-feet",
        Weight: "200 lbs",
      },
      {
        id: 2,
        name: "GSX250R ABS",
        MSRP: 7900,
        image: "/images/gsx.png",
        Engine: "50cc air-cooled single-cylinder",
        Horsepower: "300 hp",
        Torque: "245 lb-feet",
        Weight: "200 lbs",
      },
      {
        id: 3,
        name: "GSX-R600",
        MSRP: 10000,
        image: "/images/r.png",
        Engine: "50cc air-cooled single-cylinder",
        Horsepower: "300 hp",
        Torque: "245 lb-feet",
        Weight: "200 lbs",
      },
      {
        id: 4,
        name: "GSX-8R",
        MSRP: 10099,
        image: "/images/supng.png",
        Engine: "50cc air-cooled single-cylinder",
        Horsepower: "300 hp",
        Torque: "245 lb-feet",
        Weight: "200 lbs",
      },
    ],
  },
  {
    type: "Touring",
    bikes: [
      {
        id: 1,
        name: "K 1600 GTL",
        MSRP: 20000,
        image: "/images/to.png",
        Engine: "50cc air-cooled single-cylinder",
        Horsepower: "160 hp",
        Torque: "245 lb-feet",
        Weight: "707.7 lbs",
      },
      {
        id: 2,
        name: "K 1600 Grand America",
        MSRP: 25000,
        image: "/images/k.png",
        Engine: "50cc air-cooled single-cylinder",
        Horsepower: "170 hp",
        Torque: "245 lb-feet",
        Weight: "200 lbs",
      },
      {
        id: 3,
        name: "K 1600 B",
        MSRP: 22350,
        image: "/images/b.png",
        Engine: "50cc air-cooled single-cylinder",
        Horsepower: "150 hp",
        Torque: "245 lb-feet",
        Weight: "200 lbs",
      },
      {
        id: 4,
        name: "R 1250 RT",
        MSRP: 26999,
        image: "/images/rt.png",
        Engine: "50cc air-cooled single-cylinder",
        Horsepower: "140 hp",
        Torque: "245 lb-feet",
        Weight: "200 lbs",
      },
    ],
  },
];
